name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/agrohacksstuff.io"
          TAG="$(date +%Y%m%d%H%M%S)"
          jekyll build
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # Deploy to Kubernetes
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/agrohacksstuff-deployment agrohacksstuff.io=${{ secrets.DOCKERHUB_USERNAME }}/agrohacksstuff.io:$IMAGE_TAG -n default
          kubectl rollout status deployment/agrohacksstuff-deployment -n default

