name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Build the site
      - name: Setup Ruby and Jekyll
        run: |
          export GEM_HOME="$HOME/gems"
          export PATH="$GEM_HOME/bin:$PATH"
          ruby -v
          gem install bundler --user-install
          gem install jekyll --user-install
          bundle install --path "$GEM_HOME"
      
      - name: Build the site
        run: |
          export GEM_HOME="$HOME/gems"
          export PATH="$GEM_HOME/bin:$PATH"
          bundle exec jekyll build
        

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/agrohacksstuff.io"
          TAG="$(date +%Y%m%d%H%M%S)"
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # Deploy to Kubernetes
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/agrohacksstuff-deployment main-site=${{ secrets.DOCKERHUB_USERNAME }}/agrohacksstuff.io:$IMAGE_TAG -n default
          kubectl rollout status deployment/agrohacksstuff-deployment -n default

