name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Build the site
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      
      - name: Build the site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/agrohacksstuff.io"
          TAG="$(date +%Y%m%d%H%M%S)"
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # Deploy to Kubernetes
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/agrohacksstuff-deployment agrohacksstuff.io=${{ secrets.DOCKERHUB_USERNAME }}/agrohacksstuff.io:$IMAGE_TAG -n default
          kubectl rollout status deployment/agrohacksstuff-deployment -n default

